name: dev_new_with_parametrs

on: 
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Select the environment to deploy?
        required: true
        options:
          - dev
          - staging
          - prod
jobs:
  Stage-Setup:
    if: ${{ github.event.inputs.Enforcement == 'true' }}
    name: Stage Setup
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      stage: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate signed SBOM for repo content
        # Used after git clone at the begining of the pipeline
        uses: scribe-security/action-bom@master
        with:
          target: 'git:.'
          scribe-enable: true
          components: packages,files,dep
          product-key: lab-scribe-service2
          product-version: $IMAGE_TAG
          scribe-client-id: ${{ secrets.CLIENT_ID }}
          scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
          format: attest
   
    # steps: 
    #   - uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0
     
          

      # - name: Read Configuration File
      #   run: |
      #     CONFIG_FILE="dev_config.yml"
      #     while IFS= read -r line
      #     do
      #      key=$(echo "$line" | awk -F: '{print $1}')
      #      value=$(echo "$line" | awk -F: '{print $2}')
      #      export "$key=$value"
      #     done < "$CONFIG_FILE"

      # - name: Display Environment Variables
      #   run: |
      #     echo "scribe-client-id = $scribe-client-id"
      #     echo "scribe-client-secret = $scribe-client-secret"   
         
#       - name: Scm generate bom, upload to scribe
#         id: valint_bom_scm
#         uses: scribe-security/action-bom@master
# #         uses: scribe-security/action-bom@dev
#         with:
#           type: dir
#           target: ./
#           verbose: 2
#           scribe-enable: true
#           # scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID}}
#           scribe-client-id: ${{ secrets.scribe-client-id}}
#           scribe-client-secret: scribe-client-secret
#           # scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
#           product-key: "000_my_npm_repos"
#           scribe-url: ${{ env.SCRIBE_URL }}
#           scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
#           scribe-audience: ${{ env.SCRIBE_AUDIENCE }}

#       - name: build image
#         run: |
#           docker build -t my-image:latest .
       
#       - name: Read JSON file and set custom_env
#         id: set_custom_env
#         run: echo "custom_env=$(cat my_metdata.json)" >> $GITHUB_ENV
# #         run: echo "custom_env=$(cat ${{inputs.my_input_value)}}" >> $GITHUB_ENV
      
#       - name: Image generate bom, upload to scribe
#         id: valint_bom_image
#         uses: scribe-security/action-bom@master
# #         uses: scribe-security/action-bom@dev
#         with:
#           type: docker
#           target: my-image:latest
#           verbose: 2
#           format: attest
#           scribe-enable: true
#           scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
#           scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
#           product-key: "0000_my_npm_repos"
#           scribe-url: ${{ env.SCRIBE_URL }}
#           scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
#           scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
#           app-name: $LOGICAL_APP_NAME
#           app-version: $APP_VERSION
#           author-name: $AUTHOR_NAME
#           author-email: $AUTHOR_EMAIL
#           author-phone: $AUTHOR_PHONE
#           supplier-name: $SUPPLIER_NAME
#           supplier-url: $SUPPLIER_URL
#           supplier-email: $SUPPLIER_EMAIL 
#           supplier-phone: $SUPPLIER_PHONE
#           env: user_metadata
#           force: true
#         env:
#           user_metadata: ${{ env.custom_env }}
# #           DEBUG: true
