name: dev_new_env_my_npm

on: 
    workflow_dispatch:

env:
     SCRIBE_URL: "https://airflow.dev.scribesecurity.com/"
     SCRIBE_LOGIN_URL: "https://scribe-hub-dev.us.auth0.com"
     SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"


jobs:

 scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
#       - name: Scm generate bom, upload to scribe
#         id: valint_bom_scm
#         uses: scribe-security/action-bom@master
# #         uses: scribe-security/action-bom@dev
#         with:
#           type: dir
#           target: ./
#           verbose: 2
#           scribe-enable: true
#           scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID}}
#           scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
# #           scribe-client-id: iHAG3VjfnZQNECGCk0TBp8n4QBJBqiAr
# #           scribe-client-secret: VII1G3cWAw_GXSS7XDaT6i7VoFPLEkTQ0jtG8BvJdcxX6LOZJ7afzEYsSv3FKhfK
#           product-key: "000_my_npm_repos"
#           scribe-url: ${{ env.SCRIBE_URL }}
#           scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
#           scribe-audience: ${{ env.SCRIBE_AUDIENCE }}

      - name: build image
        run: |
          docker build -t my-image:latest .
       
      - name: Read JSON file and set custom_env
        id: set_custom_env
        run: echo "custom_env=$(cat my_metadata.json)" >> $GITHUB_ENV
          
          
      - name: Image generate bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
#         uses: scribe-security/action-bom@dev
        with:
          type: docker
          target: my-image:latest
          verbose: 2
          format: attest
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
#           scribe-client-id: iHAG3VjfnZQNECGCk0TBp8n4QBJBqiAr
#           scribe-client-secret: VII1G3cWAw_GXSS7XDaT6i7VoFPLEkTQ0jtG8BvJdcxX6LOZJ7afzEYsSv3FKhfK
          product-key: "0000_my_npm_repos"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
          env: test_env
          force: true
        env:
          test_env: ${{ steps.read_file_env.outputs.custom_env }}

      - uses: actions/upload-artifact@v2
        with:
          name: scribe-reports
          path: |
            ${{ steps.valint_bom_scm.outputs.OUTPUT_PATH }}
            ${{ steps.valint_bom_image.outputs.OUTPUT_PATH }}
            
#       - name: Generate SLSA provenance statement
#         id: valint_slsa_statement
#         uses: scribe-security/action-bom@master
# #         uses: scribe-security/action-bom@dev
#         with:
#           target: mongo-express:1.0.0-alpha.4
# #           format: statement-slsa
#           format: attest-slsa
#           product-key: "00_my_npm_1"

#       - uses: actions/upload-artifact@v2
#         with:
#           name: provenance
#           path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
