name: Create signed git clone and image SBOMs

on: workflow_dispatch

env:
        LOGICAL_APP_NAME: demo-project # The app name all these SBOMs will be assosiated with
        APP_VERSION: 1.0.1 # The app version all these SBOMs will be assosiated with
        # SBOM Author meta data - Optional
        AUTHOR_NAME: Alona Dodukh
        AUTHOR_EMAIL: alonadodukh@tetsemail.com
        AUTHOR_PHONE: 123-123-123-12345
        # SBOM Supplier meta data - Optional
        SUPPLIER_NAME: Scribe-Security 
        SUPPLIER_URL: www.scribesecurity.com 
        SUPPLIER_EMAIL: info@scribesecurity.com
        SUPPLIER_PHONE: 001-001-0011

jobs:

 build:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
        - uses: actions/checkout@v3

        - name: Generate signed SBOM for repo content
          uses: scribe-security/action-bom@master
          with:
                target: 'git:.'
                scribe-enable: true
                components: packages,files,dep
                scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                format: attest
                app-name: $LOGICAL_APP_NAME
                app-version: $APP_VERSION
                author-name: $AUTHOR_NAME
                author-email: $AUTHOR_EMAIL
                author-phone: $AUTHOR_PHONE
                supplier-name: $SUPPLIER_NAME
                supplier-url: $SUPPLIER_URL
                supplier-email: $SUPPLIER_EMAIL 
                supplier-phone: $SUPPLIER_PHONE

        - name: Build the Docker image
          run: docker build . -t ${{ github.repository }}:${{ github.sha }}

        - name: Generate signed SBOM for docker image
            # Used after a docker image is built
          uses: scribe-security/action-bom@master
          with:
                target: 'docker:${{ github.repository }}:${{ github.sha }}'
                scribe-enable: true
                product-key: ${{ github.repository }}:${{ github.sha }}
                scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                format: attest
                app-name: $LOGICAL_APP_NAME
                app-version: $APP_VERSION
                author-name: $AUTHOR_NAME
                author-email: $AUTHOR_EMAIL
                author-phone: $AUTHOR_PHONE
                supplier-name: $SUPPLIER_NAME
                supplier-url: $SUPPLIER_URL
                supplier-email: $SUPPLIER_EMAIL 
                supplier-phone: $SUPPLIER_PHONE

        - name: Generate SLSA provenance statement
          id: valint_slsa_statement
          uses: scribe-security/action-bom@master
          with:
                target: 'docker:${{ github.repository }}:${{ github.sha }}'
                format: statement-slsa

        - uses: actions/upload-artifact@v3
          with:
                name: provenance
                path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
