name: prod_new_env_my_npm

on: 
#     push:
    workflow_dispatch:

env:
     SCRIBE_URL: https://airflow.scribesecurity.com
     SCRIBE_LOGIN_URL: https://scribe-hub-production.us.auth0.com
     SCRIBE_AUDIENCE: api.production.scribesecurity.com

jobs:

 scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Generate dir SBOM abd upload to Scribe
        id: valint_bom_scm
        uses: scribe-security/action-bom@master
        # uses: scribe-security/action-bom@dev
        with:
          type: dir
          target: ./
          verbose: 2
          scribe-enable: true
          format: attest
          product-key: "Test_3093"
          product-version: "tets:Test_3093"
          pipeline-name: "prod_check_issue"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
          scribe-client-id: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_SECRET }}
       
      - name: build image
        run: |
          docker build -t my-image:latest .
          
      - name: Generate image bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
        # uses: scribe-security/action-bom@dev
        with:
         # format: attest, statement-cyclonedx-json, statement
          # verbose: 2
          type: docker
          target: "my-image:latest"
          format: attest
          scribe-enable: true
          product-key: "Test_3093"
          product-version: "tets:Test_3093"
          pipeline-name: "prod_check_issue"
          scribe-client-id: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_SECRET }}
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
            
      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@master
        with:
          target: "my-image:latest"
          format: attest-slsa
          product-key: "Test_3093"
          product-version: "tets:Test_3093"
          pipeline-name: "prod_check_issue"
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_SECRET }}
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}

      - uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
