name: prod_new_env_my_npm_test

on: 
#     push:
    workflow_dispatch:

env:
     SCRIBE_URL: https://airflow.scribesecurity.com
     SCRIBE_LOGIN_URL: https://scribe-hub-production.us.auth0.com
     SCRIBE_AUDIENCE: api.production.scribesecurity.com

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

 scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Scm generate bom, upload to scribe
        id: valint_bom_scm
        uses: scribe-security/action-bom@master
#         uses: scribe-security/action-bom@dev
        with:
          type: dir
          target: ./
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_SECRET }}
          product-key: "0_prod_new_my_npm"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
          product-version: "prod product version"
          pipeline-name: "prod pipeline name"
          app-name: "prod app name"
          app-version: "1.0.0 prod"

      - name: build image
        run: |
          docker build -t my-image:latest .
          
      - name: Image generate bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
#         uses: scribe-security/action-bom@dev
        with:
          type: docker
          target: my-image:latest
          format: statement-cyclonedx-json
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_PROD_NEW_CLIENT_SECRET }}
          product-key: "0_prod_new_my_npm"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
          product-version: "prod product version"
          pipeline-name: "prod pipeline name"
          app-name: "prod app name"
          app-version: "1.0.0 prod"

      - uses: actions/upload-artifact@v2
        with:
          name: scribe-reports
          path: |
            ${{ steps.valint_bom_scm.outputs.OUTPUT_PATH }}
            ${{ steps.valint_bom_image.outputs.OUTPUT_PATH }}
            
      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@master
        with:
          target: mongo-express:1.0.0-alpha.4
          format: attest-slsa
          product-key: "0_prod_new_my_npm"

      - uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
