name: stg_new_docker

on: 
#     push:
    workflow_dispatch:

env:
     SCRIBE_URL: "https://airflow.staging.scribesecurity.com/"
     SCRIBE_LOGIN_URL: "https://scribe-hub-staging.us.auth0.com"
     SCRIBE_AUDIENCE: "api.staging.scribesecurity.com"

jobs:

 scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Build the Docker image
          # run: docker build . -t ${{ github.repository }}:${{ github.sha }}
        run: |
            docker build -t my-image:latest .   

      - name: signed docker SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: my-image:latest    
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_STG_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_STG_NEW_CLIENT_SECRET }}
          product-key: "stg_docker"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
          format: statement-cyclonedx-json
          product-version: "stg_1.5"
      
      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@master
        with:
          target: my-image:latest 
          scribe-enable: true
          format: attest-slsa
          scribe-client-id: ${{ secrets.SCRIBE_STG_NEW_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_STG_NEW_CLIENT_SECRET }}
          product-key: "stg_docker"
          product-version: "stg_1.5"
          scribe-url: ${{ env.SCRIBE_URL }}
          scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
          scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
         
        
      - uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
    

      
