name: test_parametrs

on: 
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev
          - stg
          - prod
      product_version:
         description: 'Put product version'
         required: true
         default: '0.0.0'
      product_name:
         description: 'Put product name'
         required: true
         default: 'Test_product'

env:
  PRODUCT_NAME: ${{ github.event.inputs.product_name }}
  PRODUCT_VERSION: ${{ github.event.inputs.product_version }}
  # FILE_PATH: "/scribedemo/test_npm_repository/blob/master/package-lock.json"
  SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  SCRIBE_LOGIN_URL: ${{ vars.SCRIBE_LOGIN_URL }}
  SCRIBE_AUDIENCE: ${{ vars.SCRIBE_AUDIENCE }}
  AUTHOR_NAME: McCoy
  AUTHOR_EMAIL: info@scribesecurity.com
  AUTHOR_PHONE: 111-1111-11
  SUPPLIER_NAME: Scribe-Security
  SUPPLIER_URL: www.scribesecurity.com
  SUPPLIER_EMAIL: info@scribesecurity.com
  SUPPLIER_PHONE: 001-001-0011
  
        

jobs:
  build:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # - name: Read JSON file and set custom_env
      #   id: set_custom_env
      #   run: echo "FILE_PATH=$(cat my_metdata_base.json)" >> $GITHUB_ENV  

      - name: Build the Docker image
          # run: docker build . -t ${{ github.repository }}:${{ github.sha }}
        run: |
            docker build -t my-image:latest .   

      - name: Generate signed docker SBOM for docker image
        id: valint_attest_file
        uses: scribe-security/action-bom@dev
        with:
                # statement-cyclonedx-json, attest, 
                type: docker
                target: my-image:latest
                scribe-enable: true
                format: attest
                attest-default: x509-env
                product-key: $PRODUCT_NAME
                product-version: $PRODUCT_VERSION
                scribe-client-id: ${{ secrets.CLIENT_ID }}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
                scribe-url: $SCRIBE_URL
                scribe-login-url: $SCRIBE_LOGIN_URL
                scribe-audience: $SCRIBE_AUDIENCE
                author-name: $AUTHOR_NAME
                author-email: $AUTHOR_EMAIL
                author-phone: $AUTHOR_PHONE
                supplier-name: $SUPPLIER_NAME
                supplier-url: $SUPPLIER_URL
                supplier-email: $SUPPLIER_EMAIL
                supplier-phone: $SUPPLIER_PHONE 
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}  

      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@dev
        with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                type: docker
                target: my-image:latest
                # attest-slsa, statement-slsa, attest-generic
                scribe-enable: true
                format: attest-slsa
                attest-default: x509-env
                product-key: $PRODUCT_NAME
                product-version: $PRODUCT_VERSION
                scribe-client-id: ${{ secrets.CLIENT_ID }}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
                scribe-url: $SCRIBE_URL
                scribe-login-url: $SCRIBE_LOGIN_URL
                scribe-audience: $SCRIBE_AUDIENCE
                # author-name: $AUTHOR_NAME
                # author-email: $AUTHOR_EMAIL
                # author-phone: $AUTHOR_PHONE
                # supplier-name: $SUPPLIER_NAME
                # supplier-url: $SUPPLIER_URL
                # supplier-email: $SUPPLIER_EMAIL
                # supplier-phone: $SUPPLIER_PHONE
                # ca: ${{ secrets.COMPANY_CA }}
                # cert: ${{ secrets.SIGNER_CERT }}
                # key: ${{ secrets.SIGNER_KEY }}
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}  
                
      - uses: actions/upload-artifact@v3
        with:
                name: provenance
                path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
                
